#!/bin/bash
set -e

SERVER_KEY=${SERVER_KEY:-""}

#echo "ubuntu:$SERVER_PASSWORD" | chpasswd
echo "$SERVER_KEY" > /home/ubuntu/.ssh/authorized_keys
chown -R ubuntu:ubuntu /home/ubuntu/.ssh/authorized_keys
chmod 700 /home/ubuntu/.ssh/authorized_keys

#ssh id
echo "$SERVER_KEY" > /home/ubuntu/.ssh/id_rsa.pub
chown -R ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa.pub
chmod 700 /home/ubuntu/.ssh/id_rsa.pub

echo "PRIVATE_KEY" > /home/ubuntu/.ssh/id_rsa
chown -R ubuntu:ubuntu /home/ubuntu/.ssh/id_rsa
chmod 700 /home/ubuntu/.ssh/id_rsa

git config --global user.email "$USER_EMAIL"                                                                                                                                                                                                                                                                             
git config --global user.name "$USER_NAME"

if [ -n "$GIT_URL" ]; then
  # Clone the conf files into the docker container
  rm -f /home/ubuntu/workspace/*
  sudo -u ubuntu git clone $GIT_URL /home/ubuntu/workspace
  chown -R ubuntu:ubuntu /home/ubuntu/workspace
fi

exec supervisord -n
